#!/bin/bash

readonly DEPLOY_LOCATION="$1"

if [ -z "$DEPLOY_LOCATION" ]; then
  echo "You must provide the path to the directory you deploy to"
  exit 1
fi

if ! git diff-index --quiet HEAD --; then
  echo "Whoa there! You can't deploy with uncommitted changes!"
  exit 1
fi

(cd "$DEPLOY_LOCATION" && git pull -r) &&
./build-standalone-html &&
# put everything in the deploy directory
cp -r build/index.html "$DEPLOY_LOCATION/" &&
echo deployed $(git rev-parse HEAD)
