export * from './openMenu'
export * from './closeMenu'
export * from './runApp'
export * from './logFromApp'
export * from './changeEditorText'
export * from './displayOnScreen'
export * from './loadFiles'
